# Generated by Django 5.0.2 on 2024-07-24 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_question_remove_lesson_quiz_choice_quiz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='text',
            new_name='answer_choice',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='quiz_question',
        ),
    ]
