# Generated by Django 5.0.2 on 2024-07-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_text_choice_answer_choice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_image_url', models.URLField(max_length=1000)),
                ('title', models.CharField(max_length=200)),
                ('date_published', models.DateField()),
                ('length_of_read', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
    ]
